allprojects {
    repositories {
        google()
        mavenCentral()
    }
}

rootProject.buildDir = "../build"
subprojects {
    project.buildDir = "${rootProject.buildDir}/${project.name}"
}
subprojects {
    afterEvaluate { project ->
        if (project.hasProperty('android')) {
            project.android {
                if (namespace == null) {
                    namespace project.group
                }
            }
            if (project.name == "flutter_js" || project.name == "uni_links") {
                project.android {
                    compileSdkVersion 31
                    buildToolsVersion "31.0.0"
                }
            }
            Integer pluginCompileSdk = project.android.compileSdk
            project.logger.error( "Flutter plugin: " + project.name + " version: " + pluginCompileSdk)

        }
    }
}

tasks.register("clean", Delete) {
    delete rootProject.buildDir
}
